version: '3'
services:
  neo4j:
    build:
      dockerfile: neo4j/Dockerfile
      context: .
    environment:
      NEO4J_AUTH: none
    ports:
      - '7474:7474'
      - '7687:7687'
    volumes:
      - .:/app
  app:
    build: .
    volumes:
      - .:/app
    links:
      - neo4j
